version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: limites
      POSTGRES_USER: limite
      POSTGRES_PASSWORD: limite
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres_data: