server:
  port: 8081
spring:
  application:
    name: limite-svc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    username: limite
    password: limite
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      auto-offset-reset: latest
      enable-auto-commit: true

limite:
  valor: 10000

app:
  topic: transaction
  returnTopic: transaction_validate
