server:
  port: 8081
spring:
  application:
    name: limite-svc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    hikari:
      username: limite
      password: limite
  jpa:
    properties:
      hibernate:
        dialect:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      hibernate.ddl-auto: create-drop
      generate-ddl: ture
      show-sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

limite:
  valor: 2000

#  datasource:
#    username: user
#    password: password
#    url: jdbc:postgresql://localhost:5432/polardb_catalog
#    hikari:
#      connection-timeout: 2000 #ms
#      maximum-pool-size: 10