server:
  port: 8081
spring:
  application:
    name: limite-svc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    username: limite
    password: limite
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

limite:
  valor: 2000

#  datasource:
#    username: user
#    password: password
#    url: jdbc:postgresql://localhost:5432/polardb_catalog
#    hikari:
#      connection-timeout: 2000 #ms
#      maximum-pool-size: 10